BandApp/urls.py
from django.urls import path
from . import views

# Page urls
app_name = 'band'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('songs/', views.songs, name='songs'),
    path('about/', views.about, name='about'),
    path('home/', views.home, name='home'),
]

myCapstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('BandApp.urls')),
]

BandApp/models.py
from django.db import models


class Post(models.Model):
    """This class will create a post

    Parameters:
        models.Model: model

    Attributes:
        song_title: Char
        song_lyrics: Text
        date_released: date
    """
    song_title = models.CharField(max_length=100)
    song_lyrics = models.TextField()
    date_released = models.DateField()
    
    def __str__(self):
        """This function returns the title of the song

        Parameters:
            self: Post object

        Returns:
            title: Char
        """
        return self.song_title

BandApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUpForm(forms.Form):
    """This class will create a sign up form

    Parameters:
        forms.form: form

    Attributes:
        username: Char
        password: Char
        first_name: Char
    """
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=100)


    def clean_username(self):
        """This function will check if the username is available

        Parameters:
            self: SignUpForm object

        Returns:
            username: str
        """
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("A user with this username already exists. Please choose a different username.")
        return username
    

    def save(self):
        """This method will save the user to the database

        Parameters:
            self: SignUpForm object
            
        Returns:
            None
        """
        user = User.objects.create_user(
            self.cleaned_data['username'],
            None,
            self.cleaned_data['password']
        )
        user.first_name = self.cleaned_data['first_name']
        user.save()
        return user

BandApp/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import SignUpForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Post


def signup(request):
    """This function renders the signup page

    Parameters:
        request: HttpRequest object

    Returns:
        HttpResponse object
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('band:login')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form':form})


def user_login(request):
    """This function renders the login page

    Parameters:
        request: HttpRequest object

    Returns:
        HttpResponse object
    """
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
            request,
            username=username,
            password=password
        )
        if user is not None:
            login(request, user)
            return redirect(reverse('band:home'))
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'registration/login.html')


def user_logout(request):
    """This function renders the logout page

    Parameters:
        request: HttpRequest object
        
    Returns:
        HttpResponse object
    """
    logout(request)
    return redirect(reverse('band:index'))


def index(request):
    """
    This function renders the landing page
    """
    return render(request, 'band/landing.html')


def home(request):
    """
    This function renders the home page
    """
    return render(request, 'band/home.html')


def about(request):
    """
    This function renders the about page
    """
    return render(request, 'band/about.html')


def songs(request):
    """
    This function renders the songs page
    """
    posts = Post.objects.all()
    context = {
        'posts':posts
    }
    return render(request, 'band/songs.html', context)

BandApp/templates/band/about.html
<!DOCTYPE html>
<head>

    <title>About</title>

    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel = "stylesheet" integrity = "sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin = "anonymous">

    <style>
        body {
            text-align: center;
            padding: 10px;
        }
        .about{
            padding: 20px;
        }
        .members {
            color: red;
        }
    </style>

</head>
<body>
    
    <a href="{% url 'band:home' %}" class="btn btn-danger">Home</a>                   
    <a href="{% url 'band:songs' %}" class="btn btn-danger">Songs</a>                           
    <a href="{% url 'band:logout' %}" class="btn btn-danger">Logout</a>   
    
    <div class="about">
        <h1>About</h1><br>

        <h2 class="members">Members of the Band</h2>
        <ul>
            <li><strong>Mick Jagger</strong> - Harmonica - Since 1962</li>
            <li><strong>Kieth Richards</strong> - Electric Guitar - Since 1962</li>
            <li><strong>Ronnie Wood</strong> - Bass Guitar - Since 1975</li>
            <li><strong>Charlie Watts</strong> - Drum - From 1963 to 2021</li>
            <li><strong>Brian Jones</strong> - Accordion - From 1962 to 1969</li>
            <li><strong>Bill Wyman</strong> - Bass Guitar - From 1962 to 1993</li>
            <li><strong>Mick Taylor</strong> - Electric Guitar - From 1969 to 1974</li>
            <li><strong>Darryl Jones</strong> - Bass Guitar</li>
            <li><strong>Mick Avory</strong> - Acoustic Drum Kit - From 1962 to 1962</li>
            <li><strong>Tony Chapman</strong> - Acoustic Drum Kit - From 1962 to 1963</li>
            <li><strong>Ian Stewart</strong> - Piano - From 1962 to 1962</li>
            <li><strong>Dick Taylor</strong> - Former Member - From 1962 to 1962</li>
            <li><strong>Colin Golding</strong> - Former Member - From 1962 to 1963</li>
            <li><strong>Carlo Little</strong> - Former Member - From 1962 to 1963</li>
            <li><strong>Ricky Fenson</strong> - Bass Guitar - From 1962 to 1963</li>
        </ul><br>

        <h2 class="members">About the Band</h2>
        <p>The Rolling Stones are an english rock band formed in London in 1962. Their genres include Rock, Pop and Blues music</p>
    </div>

</body>
</html>

BandApp/templates/band/home.html
{% load static %}
<!DOCTYPE html>
<head>

    <title>Rolling Stones Website</title>

    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel = "stylesheet" integrity = "sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin = "anonymous">

    <style>
        body {
            text-align: center;
            padding: 10px;
        }
        .home{
            padding: 20px;
        }
        .RollingPicture:hover {
            transform: scale(1.1);
        }
    </style>

</head>
<body>

    <a href="{% url 'band:about' %}" class="btn btn-danger">About</a>
    <a href="{% url 'band:songs' %}" class="btn btn-danger">Songs</a>
    <a href="{% url 'band:logout' %}" class="btn btn-danger">Logout</a>

    <div class="home">
        <h1>The Rolling Stones Home Page</h1><br>

        <p>Click the About tab to learn about The Rolling Stones and click the Songs tab to view our database of songs.</p><br>

        <img src="{% static 'assets/stones2.jpg' %}" alt="The Rolling Stones" width="600" height="400" class="RollingPicture">

    </div>
    
</body>
</html>

BandApp/templates/band/landing.html
{% load static %}
<!DOCTYPE html>
<head>

    <title>The Rolling Stones</title>

    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel = "stylesheet" integrity = "sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin = "anonymous">

    <style>
        div {
            text-align: center;
            padding: 100px;
        }
        .RollingPicture:hover {
            transform: scale(1.1);
        }
    </style>

</head>
<body>

    <div>

        <h1>Rolling Stones Website</h1>
        <p>Click the button below to sign in</p>
            {% if user.is_authenticated %}
                <a href="{% url 'band:home' %}" class="btn btn-danger">Sign in</a>
            {% else %}
                <a href="{% url 'band:login' %}" class="btn btn-danger">Sign in</a>
            {% endif %}<br><br>
            
            <img src="{% static 'assets/stones.jpg' %}" alt="The Rolling Stones Logo" width="300" height="400" class="RollingPicture">

    </div>

</body>
</html>

BandApp/templates/band/songs.html
<!DOCTYPE html>
<head>

    <title>Songs</title>

    <link href = "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel = "stylesheet" integrity = "sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
        crossorigin = "anonymous">

    <style>
        body {
            text-align: center;
            padding: 10px;
        }
        .songs{
            padding: 20px;
        }
        .title {
            color: red;
        }
    </style>

</head>
<body>
    
    <a href="{% url 'band:home' %}" class="btn btn-danger">Home</a>                   
    <a href="{% url 'band:about' %}" class="btn btn-danger">About</a>              
    <a href="{% url 'band:logout' %}" class="btn btn-danger">Logout</a>  

    <div class="songs">
        <h1>Songs by The Rolling Stones</h1><br><br>
    </div>

    
            {% for post in posts %}
                <h2 class="title">Song Title - {{ post.song_title }}</h2>
                <p>Released on {{ post.date_released }}</p>
                <p><strong>Lyrics</strong></p>
                <p>{{ post.song_lyrics }}</p><br><br>
            {% endfor %}

</body>
</html>